// Generated by scripts/gen-mascots.mjs from assets/mascots.json. Do not edit.
export const PALETTE: Record<string, string> = {"k":"#16161e","f":"#c0caf5","s":"#e8b86d","S":"#b98a4a","m":"#3b4261","w":"#ffffff","b":"#7aa2f7","c":"#7dcfff","g":"#9aa5c8","o":"#b86e3c","r":"#f7768e","p":"#bb9af7","y":"#e0af68","t":"#73daca","d":"#565f89","n":"#9c6644","N":"#6f4628","l":"#c08a5c","W":"#eef0f6","G":"#d5dbef","h":"#c8cfe8","M":"#b4bcd9","O":"#e39a5f","P":"#f4a6b0","B":"#8fb4d8","Q":"#e2e6f3","V":"#9ea3b8"}
export const MASCOTS: Record<string, { name: string; frames: string[][] }> = {
 "sieve": {
  "name": "Sieve — the original sieve",
  "frames": [
   [
    "...............G",
    "..............G.",
    ".............G..",
    "............G...",
    "...........G....",
    "g.GGGGGGGGGGg...",
    ".gGddddddddGg...",
    "..gQMmMmMmMg....",
    "..gQmMmMmMmg....",
    "...gMmMmMmg.....",
    "....gWMWMg......",
    "......W.........",
    "...W.....W..W...",
    ".W....W.......W."
   ],
   [
    "...............G",
    "..............G.",
    ".............G..",
    "............G...",
    "...........G....",
    "g.GGGGGGGGGGg...",
    ".gGddddddddGg...",
    "..gQMmMmMmMg....",
    "..gQmMmMmMmg....",
    "...gMmMmMmg.....",
    "....gWMWMg......",
    "....W....W......",
    ".W.....W.....W..",
    "....W.......W..."
   ]
  ]
 },
 "soya": {
  "name": "Soya — the brown poodle",
  "frames": [
   [
    "....lnlnl.......",
    "...lnlnlnl......",
    "...nnnnnnnn.....",
    "..NnnnnnnnnN....",
    ".NNkkwnnkkwNN...",
    ".NNkkknnkkkNN...",
    ".NNPnnkknnPNN...",
    "..NnnnnrnnnN....",
    "...nnnnnnnn...ll",
    "....nnnnnn...lnl",
    "...nlnlnlnlnnnl.",
    "...nnnnnnnnnnn..",
    "...nn.nn..nn.nn.",
    "...NN.NN..NN.NN."
   ],
   [
    "....lnlnl.......",
    "...lnlnlnl......",
    "...nnnnnnnn.....",
    "..NnnnnnnnnN....",
    ".NNnnnnnnnnNN...",
    ".NNkkknnkkkNN...",
    ".NNPnnkknnPNN...",
    "..NnnnnrnnnN..ll",
    "...nnnnnnnn..lnl",
    "....nnnnnn...ll.",
    "...nlnlnlnlnnn..",
    "...nnnnnnnnnnn..",
    "...nn.nn..nn.nn.",
    "...NN.NN..NN.NN."
   ]
  ]
 },
 "cloud": {
  "name": "Cloud — the cat",
  "frames": [
   [
    "................",
    "..OO........OO..",
    "..OPO......OPO..",
    "..OOOOOOOOOOOO..",
    ".OOOOOOOOOOOOOO.",
    ".OOkkwOOOOkkwOO.",
    ".OOkkkOWWOkkkOO.",
    ".OPPOOWWWWOOPPO.",
    ".OOOOWWPPWWOOOO.",
    "..OOOWWWWWWOOO..",
    "...OOOWWWWOOO...",
    "..OOOWWWWWWOOO.O",
    "..OOOWWWWWWOOOOO",
    "..WWW.OOOO.WWW.."
   ],
   [
    "................",
    "..OO........OO..",
    "..OPO......OPO..",
    "..OOOOOOOOOOOO..",
    ".OOOOOOOOOOOOOO.",
    ".OOOOOOOOOOOOOO.",
    ".OOkkkOWWOkkkOO.",
    ".OPPOOWWWWOOPPO.",
    ".OOOOWWPPWWOOOO.",
    "..OOOWWWWWWOOO..",
    "...OOOWWWWOOO...",
    "..OOOWWWWWWOOOO.",
    "..OOOWWWWWWOOOOO",
    "..WWW.OOOO.WWW.."
   ]
  ]
 },
 "sifty": {
  "name": "Sifty — the mesh bowl",
  "frames": [
   [
    "......y..y......",
    "...y........y...",
    "................",
    ".ssssssssssssss.",
    "sSSSSSSSSSSSSSSs",
    "sSkkSSSSSSSSkkSs",
    "sSkwSSSSSSSSkwSs",
    "sSSSSSSkkSSSSSSs",
    ".sSSSSSSSSSSSSs.",
    "..mmmmmmmmmmmm..",
    "...m.m.m.m.m.m..",
    "................",
    ".....y....y.....",
    "................"
   ],
   [
    "...y........y...",
    "................",
    "......y..y......",
    ".ssssssssssssss.",
    "sSSSSSSSSSSSSSSs",
    "sSSSSSSSSSSSSSSs",
    "sSkkSSSSSSSSkkSs",
    "sSSSSSSkkSSSSSSs",
    ".sSSSSSSSSSSSSs.",
    "..mmmmmmmmmmmm..",
    "..m.m.m.m.m.m...",
    ".......y........",
    "................",
    "....y......y...."
   ]
  ]
 },
 "hoot": {
  "name": "Hoot — the code owl",
  "frames": [
   [
    "................",
    "...pp......pp...",
    "...pppppppppp...",
    "..pppppppppppp..",
    "..pwwwppppwwwp..",
    "..pwkwppppwkwp..",
    "..pwwwppppwwwp..",
    "..pppppyyppppp..",
    "..ppfpffffpfpp..",
    "..ppfffffffffp..",
    "...pfpfffpfpp...",
    "...pppppppppp...",
    "....yy....yy....",
    "................"
   ],
   [
    "................",
    "...pp......pp...",
    "...pppppppppp...",
    "..pppppppppppp..",
    "..pppppppppppp..",
    "..pkkkppppkkkp..",
    "..pppppppppppp..",
    "..pppppyyppppp..",
    "..ppfpffffpfpp..",
    "..ppfffffffffp..",
    "...pfpfffpfpp...",
    "...pppppppppp...",
    "....yy....yy....",
    "................"
   ]
  ]
 },
 "grit": {
  "name": "Grit — the sieve bot",
  "frames": [
   [
    ".......g........",
    ".......d........",
    "....tttttttt....",
    "...tttttttttt...",
    "...tkwttttkwt...",
    "...tttttttttt...",
    "...ttttddtttt...",
    "....tttttttt....",
    "..dmmmmmmmmmmd..",
    "..dm.m.m.m.mmd..",
    "..dmm.m.m.m.md..",
    "..dmmmmmmmmmmd..",
    "....dd....dd....",
    "................"
   ],
   [
    ".......o........",
    ".......d........",
    "....tttttttt....",
    "...tttttttttt...",
    "...tkwttttkwt...",
    "...tttttttttt...",
    "...tttddddttt...",
    "....tttttttt....",
    "..dmmmmmmmmmmd..",
    "..dmm.m.m.m.md..",
    "..dm.m.m.m.mmd..",
    "..dmmmmmmmmmmd..",
    "...dd......dd...",
    "................"
   ]
  ]
 }
}
export const DEFAULT_MASCOT = "sieve"
